<?php

namespace Drupal\googlebooks\Form;

use Drupal\Core\Form\FormStateInterface;

class ConfigForm extends ConfigFormBase {
  public function getFormId() {
    return 'googlebooks_api_settings_form';
  }
  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->getConfig();
    /**
     * Not using for Google Books API.
     */
    $form['token'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Google Books API Token'),
      '#default_value' => $config->get('token'),
      '#description' => $this->t('Your Google Books API token.'),
    ];

    $form['base_uri'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Google Books API Base URL'),
      '#default_value' => $config->get('base_uri'),
      '#description' => $this->t('Include trailing slash.'),
    ];

    $form['secret'] = [
      '#type' => 'key_select',
      '#title' => $this->t('Google Books API Secret'),
      '#default_value' => $config->get('secret'),
      '#description' => $this->t('Your Google Books API secret.')
    ];

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}